---
- name: install docker-registry system dependencies
  sudo: true
  apt: pkg={{ item }}
       state=latest
       update_cache=yes
  with_items:
    - libevent1-dev
    - libyaml-dev
    - python-dev
    - python-virtualenv
    - git-core

- name: create the docker-registry root directory
  sudo: true
  file: path=/opt/docker-registry
        owner=vagrant
        group=vagrant
        state=directory

- name: create the docker-registry virtualenv
  command: virtualenv /opt/docker-registry
           creates=/opt/docker-registry/bin/python

- name: clone the docker-registry git repository
  git: repo=https://github.com/dotcloud/docker-registry.git
       dest=/opt/docker-registry/src
       update=no
       force=no

- name: copy docker-registry config
  copy: src=config.yml
        dest=/opt/docker-registry/src/config.yml
        owner=vagrant
        group=vagrant
        mode=0644

- name: install docker-registry python packages
  pip: requirements=/opt/docker-registry/src/requirements.txt
       virtualenv=/opt/docker-registry

- name: install docker-registry upstart config
  sudo: true
  copy: src=docker-registry.conf
        dest=/etc/init/docker-registry.conf
        owner=root
        group=root
        mode=644
  notify:
    - restart docker-registry

- name: install docker-registry upstart defaults
  sudo: true
  copy: src=docker-registry.defaults
        dest=/etc/default/docker-registry
        owner=root
        group=root
        mode=644
  notify:
    - restart docker-registry

- name: start docker-registry service
  sudo: true
  service: name=docker-registry state=started
